/* ----------------ADMIN ROLE---------------------- */
CREATE TABLE ADMIN_ROLE (role_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         role_name VARCHAR(25) UNIQUE NOT NULL,
                         PRIMARY KEY (role_id));

INSERT INTO admin_role (role_name) VALUES ( 'KORISNICKI' );
INSERT INTO admin_role (role_name) VALUES ( 'PRIJEVOZNI' );
INSERT INTO admin_role (role_name) VALUES ( 'SMJESTAJNI' );

CREATE TABLE ADMIN(
                      user_name VARCHAR(20) UNIQUE NOT NULL,
                      password_hash VARCHAR(100) NOT NULL,
                      PRIMARY KEY (user_name)
);

CREATE TABLE ADMIN_ROLES(
                            admin_user_name VARCHAR(20),
                            roles_role_id INT,
                            FOREIGN KEY (admin_user_name) REFERENCES admin(user_name),
                            FOREIGN KEY (roles_role_id) REFERENCES ADMIN_ROLE(role_id),
                            PRIMARY KEY (admin_user_name, roles_role_id)
);